baseURL = "https://wat36.github.io/pages/"
title = "T.Wakasugi hugo-test"
author = "T.Wakasugi"
canonifyurls = true
paginate = 3
theme = "hugo-book"
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja-jp"
